services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: event_management_service
    ports:
      - "3307:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=password"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: uvicorn app.main:app --reload --port=8000 --host=0.0.0.0
    ports:
      - "8000:8000"
    environment:
      - SQLALCHEMY_DATABASE_URL=mysql+pymysql://root:password@db:3306/event_management_service
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
